# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            GDG Pato Branco
tagline:          ''
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'GDG Pato Branco'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gdg-pato-branco
