# Dependencies
markdown:         kramdown
rouge:            pygments

gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            GDG Pato Branco
tagline:          ''
description:      'Compartilhamos ideias, criamos conhecimento.'
logo:             /assets/GDG_square_lg.png
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'GDG Pato Branco'
  url:            https://twitter.com/mdo

# avatar
avatar  :
  - id  :         emalherbi
    name:         'Eduardo Malherbi'
    url :         http://www.gravatar.com/avatar/b4b2e05c730f60dd7ad3acb964bed758.png?s=80
  - id  :         leandro
    name:         'Leandro Parazito'
    url :         https://pt.gravatar.com/userimage/5637778/870c4611b17ed48c958cc13f1bc8b523.jpg?size=80
  - id  :         vitor
    name:         'Vitor Viganó'
    url :         http://www.gravatar.com/avatar/76bee5ccbd52cb756b22638f73383089.png?s=80
  - id  :         raoni
    name:         'Raoni Renosto'
    url :         https://s.gravatar.com/avatar/ddb2be29af32b024b023316db3b6ede5?s=80

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gdg-pato-branco
